gateway="ngtw.cytech.pro:443"
token="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiI3OWEwM2UxMy1mMjNkLTQ0ODctOTM1Ni1lMzc1Njg0N2NlNjUiLCJuYW1lIjoiR2l0aHViLTAxIiwiZXhwIjoxNzEwMjI3ODA2fQ.36q7vv2LMlWnxkmWDkuaTfLKBvKIW31eZRd11uCceoE"
